set -eux
# make clean

make JHEF405PRO EXTRA_FLAGS="-D'BUILD_KEY=b8dd283b8f0c89277f80e34a62798053' -D'RELEASE_NAME=$(git show HEAD --pretty=format:"%D %h %ci" --no-patch)' -DCLOUD_BUILD -DUSE_ALTHOLD_MODE -DUSE_DSHOT -DUSE_LED_STRIP -DUSE_OSD_HD -DUSE_PINIO -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_VTX"
